sonar.projectKey=Task-Manager
sonar.projectName=Task Manager

sonar.sources=frontend/src,backend/src
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.ts,backend/tests/**/*.test.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts,**/*.config.js,**/database/**
sonar.sourceEncoding=UTF-8
